### ISSUE TITLE
VideoMark v2.0 対応 (Docker)

### ISSUE THREAD

**Issue by kou029w** [videomark/sodium-bot#47]
- SESSION_ID の設定が行われているかどうか未確認
- LANG=ja_JP.UTF-8 以外での計測失敗

```
$ docker compose run --rm -e SESSION_ID=sodium -e LANG=C sodium-bot start https://www.youtube.com/watch?v=EqboAI-Vk-U --timeout=125

> sodium-bot@1.8.1 start
> ts-node --transpile-only start.ts https://www.youtube.com/watch?v=EqboAI-Vk-U --timeout=125

  info Wait for warm up... +0ms
  info Agree to terms. +10s
  error Current URL: chrome-extension://akaboboohklgnhnlgpbjabjcojfnkold/index.html#/onboarding +0ms
/app/node_modules/selenium-webdriver/lib/error.js:524
    let err = new ctor(data.message)
              ^
NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//button[*/@aria-label="プライバシーを尊重します"]"}
  (Session info: chrome=113.0.5672.126)
    at Object.throwDecodedError (/app/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:587:13)
    at Executor.execute (/app/node_modules/selenium-webdriver/lib/http.js:515:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Driver.execute (/app/node_modules/selenium-webdriver/lib/webdriver.js:741:17)
    at async toWireValue (/app/node_modules/selenium-webdriver/lib/webdriver.js:143:15)
    at async /app/node_modules/selenium-webdriver/lib/webdriver.js:193:16
    at async forEachKey (/app/node_modules/selenium-webdriver/lib/webdriver.js:187:9)
    at async convertKeys (/app/node_modules/selenium-webdriver/lib/webdriver.js:192:3)
    at async Driver.execute (/app/node_modules/selenium-webdriver/lib/webdriver.js:739:22) {
  remoteStacktrace: '#0 0x559d72b35133 <unknown>\n' +
    '#1 0x559d72869966 <unknown>\n' +
    '#2 0x559d728a60dc <unknown>\n' +
    '#3 0x559d728a6211 <unknown>\n' +
    '#4 0x559d728e06c4 <unknown>\n' +
    '#5 0x559d728c5bfd <unknown>\n' +
    '#6 0x559d728de1c7 <unknown>\n' +
    '#7 0x559d728c59a3 <unknown>\n' +
    '#8 0x559d7289a46a <unknown>\n' +
    '#9 0x559d7289b55e <unknown>\n' +
    '#10 0x559d72af4cae <unknown>\n' +
    '#11 0x559d72af88fe <unknown>\n' +
    '#12 0x559d72b01f20 <unknown>\n' +
    '#13 0x559d72af9923 <unknown>\n' +
    '#14 0x559d72accc0e <unknown>\n' +
    '#15 0x559d72b1cb08 <unknown>\n' +
    '#16 0x559d72b1cc97 <unknown>\n' +
    '#17 0x559d72b2d113 <unknown>\n' +
    '#18 0x7fe290025b43 <unknown>\n'
}
```

**Comment by kou029w** [comment]
> * SESSION_ID の設定が行われているかどうか未確認

- これは VideoMark v2.0 での不具合だったので https://github.com/videomark/videomark/pull/215 にて修正
